// Authored for fartola. Not ported from upstream.
//
// node:test coverage for the Phase 1 Drizzle schema (plan 02). Asserts:
// - All 9 expected tables exist after openDatabase + migrate.
// - events table has a composite primary key on (node_id, local_seq).
// - competitors has the D-11 partial unique index on
//   (competition_id, card_number) WHERE card_number IS NOT NULL.
// - C-M4: competitors.consent_status is NOT NULL DEFAULT 'explicit' and
//   accepts only the three allowed values (insert with override works,
//   insert with NULL fails the NOT NULL constraint).
//
// Uses openDatabase(':memory:') for a fresh, isolated SQLite per test.
// PATTERNS S-2 sink injection — no globals, no monkey-patches.

import { describe, test } from 'node:test';
import assert from 'node:assert/strict';

import { openDatabase } from './index.ts';

interface SqliteMasterRow {
  name: string;
}

interface PragmaTableInfoRow {
  cid: number;
  name: string;
  type: string;
  notnull: 0 | 1;
  dflt_value: string | null;
  pk: number;
}

interface PragmaIndexListRow {
  seq: number;
  name: string;
  unique: 0 | 1;
  origin: string;
  partial: 0 | 1;
}

interface PragmaIndexInfoRow {
  seqno: number;
  cid: number;
  name: string;
}

interface CompetitorRow {
  id: string;
  consent_status: string;
  consent_at_ms: number | null;
  scrubbed_at_ms: number | null;
}

const EXPECTED_TABLES = [
  'classes',
  'clubs',
  'competitions',
  'competitors',
  'config',
  'controls',
  'course_controls',
  'courses',
  'events',
];

// Phase 2.0 additions — Plan 02-01. Six new tables PLUS the
// competitors.source column. Migration 0002_phase2.sql generated by
// drizzle-kit from db/schema.ts. See .planning/phases/02-4-klubbs-mvp/
// 02-01-PLAN.md tasks 1.
const PHASE2_TABLES = [
  'eventor_competitors',
  'eventor_clubs',
  'meos_competitors',
  'meos_classes',
  'meos_clubs',
  'hired_cards',
];

describe('schema: cold-start table inventory', () => {
  test('openDatabase(:memory:) creates the 9 expected tables + __drizzle_migrations', () => {
    const handle = openDatabase(':memory:');
    try {
      const rows = handle.sqlite
        .prepare<
          unknown[],
          SqliteMasterRow
        >("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        .all();
      const names = rows.map((r) => r.name).filter((n) => !n.startsWith('sqlite_'));
      // __drizzle_migrations is created by the migrator; assert it exists separately.
      assert.ok(
        names.includes('__drizzle_migrations'),
        `missing __drizzle_migrations in ${names.join(',')}`
      );
      for (const expected of EXPECTED_TABLES) {
        assert.ok(names.includes(expected), `missing ${expected} in ${names.join(',')}`);
      }
    } finally {
      handle.close();
    }
  });
});

describe('schema: events composite primary key', () => {
  test('events table_info reports PK on node_id (pk=1) and local_seq (pk=2)', () => {
    const handle = openDatabase(':memory:');
    try {
      const cols = handle.sqlite
        .prepare<unknown[], PragmaTableInfoRow>('PRAGMA table_info(events)')
        .all();
      const nodeId = cols.find((c) => c.name === 'node_id');
      const localSeq = cols.find((c) => c.name === 'local_seq');
      assert.ok(nodeId, 'node_id column missing');
      assert.ok(localSeq, 'local_seq column missing');
      // SQLite numbers composite PK members 1..N in the order they appear.
      assert.equal(nodeId.pk, 1, `expected node_id.pk=1, got ${nodeId.pk}`);
      assert.equal(localSeq.pk, 2, `expected local_seq.pk=2, got ${localSeq.pk}`);
    } finally {
      handle.close();
    }
  });
});

describe('schema: competitors partial unique index (D-11)', () => {
  test('competitors_card_per_comp is UNIQUE + PARTIAL on (competition_id, card_number)', () => {
    const handle = openDatabase(':memory:');
    try {
      const indexes = handle.sqlite
        .prepare<unknown[], PragmaIndexListRow>('PRAGMA index_list(competitors)')
        .all();
      const target = indexes.find((i) => i.name === 'competitors_card_per_comp');
      assert.ok(target, `competitors_card_per_comp not found in ${JSON.stringify(indexes)}`);
      assert.equal(target.unique, 1, 'expected unique=1');
      assert.equal(target.partial, 1, 'expected partial=1 (D-11)');

      const cols = handle.sqlite
        .prepare<unknown[], PragmaIndexInfoRow>('PRAGMA index_info(competitors_card_per_comp)')
        .all();
      const colNames = cols.sort((a, b) => a.seqno - b.seqno).map((c) => c.name);
      assert.deepEqual(colNames, ['competition_id', 'card_number']);
    } finally {
      handle.close();
    }
  });
});

describe('schema: competitors.consent_status (C-M4)', () => {
  test('consent_status defaults to "explicit" when omitted from INSERT', () => {
    const handle = openDatabase(':memory:');
    try {
      // Seed FK parents first (competitions + classes).
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare("INSERT INTO classes (id, competition_id, name) VALUES ('cl1', 'c1', 'H21')")
        .run();
      handle.sqlite
        .prepare(
          "INSERT INTO competitors (id, competition_id, name, class_id) VALUES ('comp1', 'c1', 'Anna', 'cl1')"
        )
        .run();
      const row = handle.sqlite
        .prepare<
          unknown[],
          CompetitorRow
        >('SELECT id, consent_status, consent_at_ms, scrubbed_at_ms FROM competitors WHERE id=?')
        .get('comp1');
      assert.ok(row, 'expected row for comp1');
      assert.equal(row.consent_status, 'explicit');
      assert.equal(row.consent_at_ms, null);
      assert.equal(row.scrubbed_at_ms, null);
    } finally {
      handle.close();
    }
  });

  test('consent_status accepts "pending_first_read" override', () => {
    const handle = openDatabase(':memory:');
    try {
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare("INSERT INTO classes (id, competition_id, name) VALUES ('cl1', 'c1', 'H21')")
        .run();
      handle.sqlite
        .prepare(
          "INSERT INTO competitors (id, competition_id, name, class_id, consent_status) VALUES ('comp2', 'c1', 'Bo', 'cl1', 'pending_first_read')"
        )
        .run();
      const row = handle.sqlite
        .prepare<
          unknown[],
          CompetitorRow
        >('SELECT id, consent_status, consent_at_ms, scrubbed_at_ms FROM competitors WHERE id=?')
        .get('comp2');
      assert.ok(row);
      assert.equal(row.consent_status, 'pending_first_read');
    } finally {
      handle.close();
    }
  });

  test('consent_status=NULL is rejected by NOT NULL constraint', () => {
    const handle = openDatabase(':memory:');
    try {
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare("INSERT INTO classes (id, competition_id, name) VALUES ('cl1', 'c1', 'H21')")
        .run();
      assert.throws(() => {
        handle.sqlite
          .prepare(
            "INSERT INTO competitors (id, competition_id, name, class_id, consent_status) VALUES ('comp3', 'c1', 'Ce', 'cl1', NULL)"
          )
          .run();
      }, /NOT NULL constraint failed: competitors\.consent_status/);
    } finally {
      handle.close();
    }
  });
});

// ---------------------------------------------------------------------------
// Phase 2.0 schema extensions — Plan 02-01 task 1.
// ---------------------------------------------------------------------------

describe('schema (phase 2): six new tables present after migration', () => {
  test('eventor_competitors, eventor_clubs, meos_*, hired_cards all exist', () => {
    const handle = openDatabase(':memory:');
    try {
      const rows = handle.sqlite
        .prepare<
          unknown[],
          SqliteMasterRow
        >("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        .all();
      const names = rows.map((r) => r.name);
      for (const expected of PHASE2_TABLES) {
        assert.ok(names.includes(expected), `missing ${expected} in ${names.join(',')}`);
      }
    } finally {
      handle.close();
    }
  });
});

describe('schema (phase 2): competitors.source column', () => {
  test('source defaults to "walkup" — backfill semantic for pre-2.0 rows', () => {
    const handle = openDatabase(':memory:');
    try {
      // Seed competition + class.
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare("INSERT INTO classes (id, competition_id, name) VALUES ('cl1', 'c1', 'H21')")
        .run();
      // Insert competitor WITHOUT specifying source — default should fire.
      handle.sqlite
        .prepare(
          "INSERT INTO competitors (id, competition_id, name, class_id) VALUES ('p2-comp1', 'c1', 'Pre20', 'cl1')"
        )
        .run();
      const row = handle.sqlite
        .prepare<unknown[], { source: string }>('SELECT source FROM competitors WHERE id=?')
        .get('p2-comp1');
      assert.ok(row);
      assert.equal(row.source, 'walkup');
    } finally {
      handle.close();
    }
  });

  test('source accepts "entrylist" and "meos" overrides', () => {
    const handle = openDatabase(':memory:');
    try {
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare("INSERT INTO classes (id, competition_id, name) VALUES ('cl1', 'c1', 'H21')")
        .run();
      handle.sqlite
        .prepare(
          "INSERT INTO competitors (id, competition_id, name, class_id, source) VALUES ('p2-comp2', 'c1', 'EL', 'cl1', 'entrylist')"
        )
        .run();
      handle.sqlite
        .prepare(
          "INSERT INTO competitors (id, competition_id, name, class_id, source) VALUES ('p2-comp3', 'c1', 'M', 'cl1', 'meos')"
        )
        .run();
      const rows = handle.sqlite
        .prepare<
          unknown[],
          { id: string; source: string }
        >('SELECT id, source FROM competitors WHERE id IN (?, ?) ORDER BY id')
        .all('p2-comp2', 'p2-comp3');
      assert.equal(rows.length, 2);
      assert.equal(rows[0]?.source, 'entrylist');
      assert.equal(rows[1]?.source, 'meos');
    } finally {
      handle.close();
    }
  });
});

describe('schema (phase 2): hired_cards compound PK', () => {
  test('same card_number under different competition_id is allowed', () => {
    const handle = openDatabase(':memory:');
    try {
      // Two competitions.
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c2', 't', '2026-05-15', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare(
          'INSERT INTO hired_cards (competition_id, card_number, marked_at_ms) VALUES (?, ?, ?)'
        )
        .run('c1', 12345, 1);
      handle.sqlite
        .prepare(
          'INSERT INTO hired_cards (competition_id, card_number, marked_at_ms) VALUES (?, ?, ?)'
        )
        .run('c2', 12345, 2);
      const rows = handle.sqlite
        .prepare<
          unknown[],
          { competition_id: string }
        >('SELECT competition_id FROM hired_cards ORDER BY competition_id')
        .all();
      assert.equal(rows.length, 2);
    } finally {
      handle.close();
    }
  });

  test('same card_number under same competition_id is rejected', () => {
    const handle = openDatabase(':memory:');
    try {
      handle.sqlite
        .prepare(
          "INSERT INTO competitions (id, name, date, receipt_template, auto_print, created_at_ms) VALUES ('c1', 't', '2026-05-14', 'classic', 0, 1)"
        )
        .run();
      handle.sqlite
        .prepare(
          'INSERT INTO hired_cards (competition_id, card_number, marked_at_ms) VALUES (?, ?, ?)'
        )
        .run('c1', 99999, 1);
      assert.throws(() => {
        handle.sqlite
          .prepare(
            'INSERT INTO hired_cards (competition_id, card_number, marked_at_ms) VALUES (?, ?, ?)'
          )
          .run('c1', 99999, 2);
      }, /UNIQUE constraint|PRIMARY KEY/);
    } finally {
      handle.close();
    }
  });
});

describe('schema (phase 2): eventor_competitors indexes', () => {
  // Plan 02-09 task 1: the UNIQUE was dropped because real federation
  // data has legitimate duplicate si_cards (family-shared, rental pool,
  // replacement cards). The index stays partial and on the same column —
  // lookup performance unchanged — but no longer enforces uniqueness.
  test('partial non-unique index on si_card (WHERE si_card IS NOT NULL)', () => {
    const handle = openDatabase(':memory:');
    try {
      const indexes = handle.sqlite
        .prepare<unknown[], PragmaIndexListRow>('PRAGMA index_list(eventor_competitors)')
        .all();
      const idx = indexes.find((i) => i.name === 'idx_eventor_si_card_lookup');
      assert.ok(idx, `idx_eventor_si_card_lookup not found in ${JSON.stringify(indexes)}`);
      assert.equal(idx.partial, 1, 'idx_eventor_si_card_lookup must be partial');
      assert.equal(idx.unique, 0, 'idx_eventor_si_card_lookup must NOT be unique');
      const old = indexes.find((i) => i.name === 'idx_eventor_si_card');
      assert.equal(old, undefined, 'old UNIQUE idx_eventor_si_card must be dropped');
    } finally {
      handle.close();
    }
  });

  test('non-unique index on (family_name, given_name) exists', () => {
    const handle = openDatabase(':memory:');
    try {
      const indexes = handle.sqlite
        .prepare<unknown[], PragmaIndexListRow>('PRAGMA index_list(eventor_competitors)')
        .all();
      const idx = indexes.find((i) => i.name === 'idx_eventor_name');
      assert.ok(idx, `idx_eventor_name not found in ${JSON.stringify(indexes)}`);
      const cols = handle.sqlite
        .prepare<unknown[], PragmaIndexInfoRow>('PRAGMA index_info(idx_eventor_name)')
        .all()
        .sort((a, b) => a.seqno - b.seqno)
        .map((c) => c.name);
      assert.deepEqual(cols, ['family_name', 'given_name']);
    } finally {
      handle.close();
    }
  });
});

describe('schema (phase 2.1): course_replacements table + Phase 2.1 columns', () => {
  test('course_replacements table exists with unique index', () => {
    const handle = openDatabase(':memory:');
    try {
      const rows = handle.sqlite
        .prepare<
          unknown[],
          SqliteMasterRow
        >("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        .all();
      const names = rows.map((r) => r.name);
      assert.ok(
        names.includes('course_replacements'),
        `course_replacements missing in ${names.join(',')}`
      );
      // Unique index must exist.
      const indexes = handle.sqlite
        .prepare<unknown[], PragmaIndexListRow>('PRAGMA index_list(course_replacements)')
        .all();
      const uniqueIdx = indexes.find(
        (i) => i.name === 'course_replacements_unique' && i.unique === 1
      );
      assert.ok(
        uniqueIdx,
        `course_replacements_unique index not found in ${JSON.stringify(indexes)}`
      );
    } finally {
      handle.close();
    }
  });

  test('classes has first_start_ms, start_interval_sec, max_time_sec columns (nullable)', () => {
    const handle = openDatabase(':memory:');
    try {
      const cols = handle.sqlite
        .prepare<unknown[], PragmaTableInfoRow>('PRAGMA table_info(classes)')
        .all();
      for (const col of ['first_start_ms', 'start_interval_sec', 'max_time_sec']) {
        const found = cols.find((c) => c.name === col);
        assert.ok(found, `classes.${col} column missing`);
        assert.equal(found.notnull, 0, `classes.${col} must be nullable`);
      }
    } finally {
      handle.close();
    }
  });

  test('competitors has start_time_ms column (nullable)', () => {
    const handle = openDatabase(':memory:');
    try {
      const cols = handle.sqlite
        .prepare<unknown[], PragmaTableInfoRow>('PRAGMA table_info(competitors)')
        .all();
      const col = cols.find((c) => c.name === 'start_time_ms');
      assert.ok(col, 'competitors.start_time_ms column missing');
      assert.equal(col.notnull, 0, 'competitors.start_time_ms must be nullable');
    } finally {
      handle.close();
    }
  });

  test('competitions has liveresultat_id, liveresultat_pwd, eventor_event_id, timing_format columns', () => {
    const handle = openDatabase(':memory:');
    try {
      const cols = handle.sqlite
        .prepare<unknown[], PragmaTableInfoRow>('PRAGMA table_info(competitions)')
        .all();
      for (const col of ['liveresultat_id', 'liveresultat_pwd', 'eventor_event_id']) {
        const found = cols.find((c) => c.name === col);
        assert.ok(found, `competitions.${col} column missing`);
        assert.equal(found.notnull, 0, `competitions.${col} must be nullable`);
      }
      const timingFmt = cols.find((c) => c.name === 'timing_format');
      assert.ok(timingFmt, 'competitions.timing_format column missing');
      assert.equal(timingFmt.dflt_value, "'seconds'", "timing_format default must be 'seconds'");
    } finally {
      handle.close();
    }
  });
});

describe('schema (phase 2): meos_* tables have no competition_id', () => {
  test('meos_competitors / meos_classes / meos_clubs lack competition_id', () => {
    const handle = openDatabase(':memory:');
    try {
      for (const table of ['meos_competitors', 'meos_classes', 'meos_clubs']) {
        const cols = handle.sqlite
          .prepare<unknown[], PragmaTableInfoRow>(`PRAGMA table_info(${table})`)
          .all();
        const compIdCol = cols.find((c) => c.name === 'competition_id');
        assert.equal(
          compIdCol,
          undefined,
          `${table} must NOT have competition_id (Pattern 6 — global session state)`
        );
      }
    } finally {
      handle.close();
    }
  });
});
