// Authored for fartola. Not ported from upstream.
//
// Drizzle schema-as-TS for the Phase 1 single-laptop training MVP. Defines
// the events table (immutable, append-only) plus seven mutable config
// tables (competitions, classes, controls, courses, course_controls,
// competitors, clubs) and one internal singleton config table (config)
// for storing the node_id across restarts.
//
// Locked by:
// - .planning/adr/0003-event-sourcing-as-core-data-model.md (events table
//   is immutable — enforced by triggers in 0001_append_only_triggers.sql)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-09
//   (mutable config tables — Phase 1 uses CRUD; Phase 2 will layer Yjs
//   on top of these tables for multi-operator editing)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-10
//   (Drizzle ORM on better-sqlite3, schema-as-TS, built-in migrations)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-11
//   (card-to-competitor matching = hybrid; partial unique index on
//   competitors.(competition_id, card_number) where card_number IS NOT NULL)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-12
//   (DNF/MP is a pure projection over the event log — no precomputed
//   status column on competitors)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-15
//   (wizard fields: name + date + receipt_template + auto_print)
// - .planning/phases/01-single-laptop-training-mvp/01-REVIEWS.md §C-H1
//   (append-only triggers live in a SEPARATE migration file
//   0001_append_only_triggers.sql — drizzle-kit's schema-as-TS has no
//   trigger primitive, so the planner-original scheme of appending the
//   trigger SQL to 0000_initial.sql was fragile: future `db:generate`
//   regenerates 0000 and erases the triggers. The 0001 file is never
//   regenerated by drizzle-kit, so it survives every `db:generate` run)
// - .planning/phases/01-single-laptop-training-mvp/01-REVIEWS.md §C-H5
//   (shared-types is a pure DTO package. Drizzle row inference lives in
//   apps/edge/src/db/types.ts — NOT in packages/shared-types. This file
//   has zero downward dependencies on shared-types and the EventPayload
//   union is defined locally so the schema stays self-contained)
// - .planning/phases/01-single-laptop-training-mvp/01-REVIEWS.md §C-M4
//   (competitors.consent_status TEXT NOT NULL DEFAULT 'explicit'; values
//   are 'explicit' (walk-up checkbox), 'pending_first_read' (EntryList
//   import — operator confirms on first card_read), 'confirmed_on_read'
//   (after one-time confirmation toast). Plan 05 sets 'pending_first_read';
//   plan 14 surfaces the toast that flips to 'confirmed_on_read')
// - .planning/research/architecture.md §"Event log schema"
//   (columns: node_id, local_seq, competition_id, event_type,
//   event_time_ms, recorded_at_ms, payload; PRIMARY KEY (node_id,
//   local_seq); indexes on event_time_ms, competition_id, and
//   (competition_id, event_type))
//
// REQ-EVT-001..004 (event log shape + immutability)
// REQ-EVT-CMP-001 (competitor/class/course config)
// REQ-PRIV-001 (consent_at_ms on competitor row)
// REQ-PRIV-002 (scrubbable PII columns — name + club nulled by plan 17)

import { sql } from 'drizzle-orm';
import {
  sqliteTable,
  text,
  integer,
  primaryKey,
  index,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import type { NdjsonPunch, HalfDayClock } from '@fartola/sportident';

// ---------------------------------------------------------------------------
// EventPayload — discriminated union stored as JSON in events.payload.
//
// The `card_read` arm mirrors Phase 0's CardReadEvent shape exactly (codex
// C-H2 — plan 06 wires the bridge that produces these payloads; locking the
// type at the schema layer means a wrong-shape insert is a compile error).
//
// Phase 1 adds five non-Phase-0 event types that flow only through
// apps/edge — they never travel over the NDJSON wire from packages/sportident.
// All keys snake_case at the JSON boundary per PATTERNS S-6.
// ---------------------------------------------------------------------------

export type EventPayload =
  | {
      event_type: 'card_inserted';
      card_number: number;
      card_type: string;
    }
  | {
      // Phase 2.1 — voided leg. Emitted by
      // POST /api/competitions/:id/competitors/:cid/void-leg.
      // The reducer subtracts min(actual_leg_ms, max_seconds * 1000) from
      // elapsed_time_ms. Reversible via leg_unvoided.
      event_type: 'leg_voided';
      competitor_id: string;
      /** SPORTident control code of the leg being voided. */
      control_code: number;
      /** Optional time cap for this leg in seconds (null = uncapped). */
      max_seconds: number | null;
      /** Optional operator reason. */
      reason?: string;
    }
  | {
      // Phase 2.1 — unvoid leg. Reverses a prior leg_voided event.
      event_type: 'leg_unvoided';
      competitor_id: string;
      control_code: number;
    }
  | {
      event_type: 'card_read';
      card_number: number;
      card_type: string;
      start: HalfDayClock | null;
      finish: HalfDayClock | null;
      check: HalfDayClock | null;
      clear: HalfDayClock | null;
      punch_count: number;
      punches: NdjsonPunch[];
      card_holder: Record<string, unknown> | null;
      card_series_byte?: number;
      uid?: number;
    }
  | {
      event_type: 'card_removed';
      card_number: number;
    }
  | {
      event_type: 'card_bound';
      competitor_id: string;
      card_number: number;
      walkup: boolean;
      consent_at_ms: number;
    }
  | {
      event_type: 'manual_dnf';
      competitor_id: string;
      reason: string;
    }
  | {
      event_type: 'un_dnf';
      competitor_id: string;
    }
  | {
      // Phase 2.0 generalization of manual_dnf — operator asserts one of the
      // five manual statuses (DNF/DNS/DQ/CANCEL/MAX) with optional reason.
      // The reducer prefers manual_status_set over the legacy manual_dnf;
      // both write to the same view.manual_status field so old event logs
      // keep replaying correctly.
      event_type: 'manual_status_set';
      competitor_id: string;
      status: 'DNF' | 'DNS' | 'DQ' | 'CANCEL' | 'MAX';
      reason: string;
    }
  | {
      // Phase 2.0 generalization of un_dnf — clears whatever manual override
      // is in force and re-derives status from the latest card_read (or PEND
      // when no card_read has landed).
      event_type: 'clear_manual_status';
      competitor_id: string;
    }
  | {
      // Phase 2.1 (2026-05-18) — race-phase flip. Emitted by POST
      // /api/competitions/:id/start-race. The event is the audit-trail
      // source of truth; the competitions.race_started_at_ms column is a
      // denormalised cache the reducer reads on every reduce() pass.
      //
      // Operator UI guarantees one race_started event per competition by
      // disabling the button after the flip. The reducer is idempotent on
      // duplicates: applying it twice just rewrites the same timestamp.
      event_type: 'race_started';
      started_at_ms: number;
    }
  | {
      // Phase 2.1 (2026-05-18) — race-phase rollback. Lets the operator
      // undo an accidental start (e.g. tested the button before the real
      // race began). The reducer nulls competitions.race_started_at_ms on
      // apply; subsequent card_reads return to identity-scan semantics.
      event_type: 'race_reset';
      previous_started_at_ms: number;
    }
  | {
      event_type: 'frame_error';
      reason: string;
      raw: string;
    }
  | {
      event_type: 'connection_changed';
      state: 'opening' | 'open' | 'error' | 'closed';
      error?: string;
    }
  | {
      event_type: 'consent_confirmed';
      competitor_id: string;
      prior_consent_status: 'pending_first_read';
    };

// ---------------------------------------------------------------------------
// competitions — mutable. D-09 (config tables are CRUD; punches are events).
// D-15 (wizard) locks the four mutable fields. UI-SPEC §Auto-print toggle
// defaults auto_print to 0 (OFF); UI-SPEC §"Receipt template DEFAULT" pins
// receipt_template to 'classic' on create.
// ---------------------------------------------------------------------------

export const competitions = sqliteTable('competitions', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  /** ISO date 'YYYY-MM-DD' — UI-SPEC §Visual Anchors. */
  date: text('date').notNull(),
  receiptTemplate: text('receipt_template').notNull().default('classic'),
  autoPrint: integer('auto_print', { mode: 'boolean' }).notNull().default(false),
  createdAtMs: integer('created_at_ms').notNull(),
  /** Phase 2.1 (2026-05-18) — race-phase gate.
   *
   * NULL = pre-race phase. card_read events are kept in the event log
   * (full audit trail) but the reducer does NOT run dnfMp.detectStatus
   * against them — they're identity scans, not scoring events. This is
   * the universal "race zero-time" pattern (MeOS calls it `firstStart`
   * / "tävlingens nolltid").
   *
   * Non-null = race has started. card_read events at or after this
   * timestamp run through detectStatus normally and produce OK/MP/DNF.
   *
   * Flipped by POST /api/competitions/:id/start-race which atomically
   * inserts a `race_started` event AND updates this column. The event
   * is the audit-trail source of truth; the column is a denormalised
   * cache so the reducer + frontend don't have to scan the log to know
   * the current phase. */
  raceStartedAtMs: integer('race_started_at_ms'),
  /** Phase 2.1 — liveresultat.orientering.se competition ID for result push. */
  liveresultatId: text('liveresultat_id'),
  /** Phase 2.1 — liveresultat upload password. */
  liveresultatPwd: text('liveresultat_pwd'),
  /** Phase 2.1 — linked Eventor event ID for result/start-list push. */
  eventorEventId: integer('eventor_event_id'),
  /** Phase 2.1 D-17 — display format for elapsed times: 'seconds' or 'tenths'.
   * Sprint events typically use 'tenths'; road/forest use 'seconds'. */
  timingFormat: text('timing_format').default('seconds'),
});

// ---------------------------------------------------------------------------
// classes — mutable. Cascade-deletes when the parent competition is deleted
// (which only happens in dev / test fixture setup; production never deletes
// a real competition).
// ---------------------------------------------------------------------------

export const classes = sqliteTable(
  'classes',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    shortName: text('short_name'),
    /** Phase 2.1 D-05 — epoch ms of the first start slot for this class.
     * NULL = no start list drawn yet. */
    firstStartMs: integer('first_start_ms'),
    /** Phase 2.1 D-05 — seconds between start slots (e.g. 60 for 1-minute
     * intervals). NULL = no start list drawn yet. */
    startIntervalSec: integer('start_interval_sec'),
    /** Phase 2.1 D-08 — class time cap in seconds. NULL = no cap.
     * Reducer promotes OK/MP to MAX when elapsed_time_ms/1000 > maxTimeSec. */
    maxTimeSec: integer('max_time_sec'),
  },
  (t) => [uniqueIndex('classes_name_per_comp').on(t.competitionId, t.name)]
);

// ---------------------------------------------------------------------------
// controls — mutable. Code is the SportIdent control code (typically 31-150).
// ---------------------------------------------------------------------------

export const controls = sqliteTable(
  'controls',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    code: integer('code').notNull(),
  },
  (t) => [uniqueIndex('controls_code_per_comp').on(t.competitionId, t.code)]
);

// ---------------------------------------------------------------------------
// courses — mutable. A course typically maps 1:1 to a class but XML import
// may assign later (D-03), so class_id is NULL-able.
// ---------------------------------------------------------------------------

export const courses = sqliteTable('courses', {
  id: text('id').primaryKey(),
  competitionId: text('competition_id')
    .notNull()
    .references(() => competitions.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  classId: text('class_id').references(() => classes.id),
  lengthM: integer('length_m'),
  climbM: integer('climb_m'),
});

// ---------------------------------------------------------------------------
// course_controls — mutable. Ordered list of controls per course. order_idx
// is 0-based.
// ---------------------------------------------------------------------------

export const courseControls = sqliteTable(
  'course_controls',
  {
    id: text('id').primaryKey(),
    courseId: text('course_id')
      .notNull()
      .references(() => courses.id, { onDelete: 'cascade' }),
    controlId: text('control_id')
      .notNull()
      .references(() => controls.id, { onDelete: 'cascade' }),
    orderIdx: integer('order_idx').notNull(),
  },
  (t) => [uniqueIndex('course_controls_order').on(t.courseId, t.orderIdx)]
);

// ---------------------------------------------------------------------------
// competitors — mutable. REQ-PRIV-001 (consent_at_ms), REQ-PRIV-002 (name +
// club are scrubbable in plan 17). C-M4 locks consent_status. D-11 partial
// unique index on (competition_id, card_number) where card_number IS NOT NULL.
// ---------------------------------------------------------------------------

export const competitors = sqliteTable(
  'competitors',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    /** Scrubbable PII per REQ-PRIV-002 (plan 17 nulls / anonymises). */
    name: text('name').notNull(),
    /** Scrubbable PII per REQ-PRIV-002 (plan 17 nulls / anonymises). */
    club: text('club'),
    classId: text('class_id')
      .notNull()
      .references(() => classes.id),
    /** NULL = no card pre-assigned; bound at walk-up or first read (D-11). */
    cardNumber: integer('card_number'),
    /** REQ-PRIV-001 — timestamp of recorded consent; NULL allowed when
     * consent_status='pending_first_read' (the operator has not yet
     * confirmed for this competitor). */
    consentAtMs: integer('consent_at_ms'),
    /** C-M4: 'explicit' (walk-up checkbox), 'pending_first_read'
     * (EntryList import), 'confirmed_on_read' (one-time toast confirmed). */
    consentStatus: text('consent_status', {
      enum: ['explicit', 'pending_first_read', 'confirmed_on_read'],
    })
      .notNull()
      .default('explicit'),
    /** REQ-PRIV-002 — set when PII columns nulled by plan 17 daily scrub;
     * non-null indicates an anonymized row. */
    scrubbedAtMs: integer('scrubbed_at_ms'),
    /** Phase 2.0 D-MOP-3 — origin of this competitor row:
     * 'walkup'    — created by the operator at the registration desk
     * 'entrylist' — imported from an IOF XML 3.0 EntryList (Phase 1 plan 05)
     * 'meos'      — auto-merged from MeOS via MOP receiver (Phase 2 plan 04)
     * Defaults to 'walkup' so pre-2.0 rows backfill cleanly. */
    source: text('source', { enum: ['walkup', 'entrylist', 'meos'] })
      .notNull()
      .default('walkup'),
    /** Phase 2.1 D-05 — assigned start time as epoch ms. NULL = not drawn
     * (walk-up or late entry without a start slot). */
    startTimeMs: integer('start_time_ms'),
  },
  (t) => [
    // D-11 partial unique index: same physical card cannot be bound to two
    // competitors within a single competition. NULL card_number is allowed
    // multiply (un-attached competitors).
    uniqueIndex('competitors_card_per_comp')
      .on(t.competitionId, t.cardNumber)
      .where(sql`${t.cardNumber} IS NOT NULL`),
  ]
);

// ---------------------------------------------------------------------------
// clubs — mutable autocomplete cache. UI-SPEC §"Walk-up modal" backs the
// club autocomplete with this table. name is the natural key (primary key
// directly); last_seen_at_ms is updated on every bind/walk-up so stale
// clubs naturally rank lower in the autocomplete sort.
// ---------------------------------------------------------------------------

export const clubs = sqliteTable('clubs', {
  name: text('name').primaryKey(),
  lastSeenAtMs: integer('last_seen_at_ms').notNull(),
});

// ---------------------------------------------------------------------------
// config — internal singleton key/value store. Plan 02 uses key='node_id'
// for the per-install node identifier (stable across restarts — REQ-OPS-002).
// No FKs; intentionally simple.
// ---------------------------------------------------------------------------

export const config = sqliteTable('config', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

// ---------------------------------------------------------------------------
// events — immutable, append-only. PRIMARY KEY (node_id, local_seq) per
// research/architecture.md. competition_id is nullable (pre-competition
// events from the idle bridge). Append-only invariant enforced by the
// hand-authored 0001_append_only_triggers.sql migration (C-H1).
// ---------------------------------------------------------------------------

export const events = sqliteTable(
  'events',
  {
    nodeId: text('node_id').notNull(),
    localSeq: integer('local_seq').notNull(),
    /** NULL = pre-competition event (e.g. idle bridge connection_changed). */
    competitionId: text('competition_id').references(() => competitions.id),
    eventType: text('event_type').notNull(),
    /** Host clock at the event itself (ms epoch). */
    eventTimeMs: integer('event_time_ms').notNull(),
    /** Host clock at insert time (ms epoch). May differ for replayed events. */
    recordedAtMs: integer('recorded_at_ms').notNull(),
    payload: text('payload', { mode: 'json' }).notNull().$type<EventPayload>(),
  },
  (t) => [
    primaryKey({ columns: [t.nodeId, t.localSeq] }),
    index('idx_events_time').on(t.eventTimeMs),
    index('idx_events_comp').on(t.competitionId),
    index('idx_events_comp_type').on(t.competitionId, t.eventType),
  ]
);

// ===========================================================================
// Phase 2.0 — 4-klubbs MVP extensions (Plan 02-01).
// ===========================================================================
//
// Six new tables landed in migration 0002_phase2.sql so subsequent plans
// (02 walkup, 03 MIP, 04 MOP, 05 hyrbricka toast) can land without further
// schema migrations. Locked by:
//
// - .planning/phases/02-4-klubbs-mvp/02-CONTEXT.md D-EV-1/2/3 (Eventor
//   on-boot fetch + 7-day staleness)
// - .planning/phases/02-4-klubbs-mvp/02-CONTEXT.md D-MOP-1 (shadow
//   meos_* tables; auto-merge into competitors with source='meos')
// - .planning/phases/02-4-klubbs-mvp/02-CONTEXT.md D-HB-1 (junction table
//   hired_cards with compound PK + contact info MeOS lacks)
// - .planning/adr/0009-eventor-runner-cache.md (PII trade-off for the
//   national runner DB cache)

// ---------------------------------------------------------------------------
// eventor_clubs — mutable autocomplete cache of Swedish orienteering clubs.
// PK = Eventor numeric club id. Populated from /api/export/clubs?version=3.0.
// FK target for eventor_competitors.club_id.
// ---------------------------------------------------------------------------

export const eventorClubs = sqliteTable('eventor_clubs', {
  clubId: integer('club_id').primaryKey(),
  name: text('name').notNull(),
  shortName: text('short_name'),
  /** Display name Eventor recommends for media/results (may be NULL). */
  mediaName: text('media_name'),
  /** Parent district / region id (NULL for top-level clubs). */
  parentId: integer('parent_id'),
  /** Eventor `modifyTime` parsed to epoch ms; lets cache refresh diff. */
  modifyDateMs: integer('modify_date_ms').notNull(),
});

// ---------------------------------------------------------------------------
// eventor_competitors — national runner cache (~252 919 rows after a full
// refresh; ~96 918 with SI cards). PK = Eventor numeric person id.
//
// PII per REQ-PRIV-002 BUT NOT scrub-eligible — re-fetchable from Eventor
// any time; ADR-0009 records the trade-off (local-only cache, no
// phone/email, weekly refresh respects Eventor ToS).
// ---------------------------------------------------------------------------

export const eventorCompetitors = sqliteTable(
  'eventor_competitors',
  {
    personId: integer('person_id').primaryKey(),
    /** PII per REQ-PRIV-002 — re-fetchable; NOT scrubbed (ADR-0009). */
    familyName: text('family_name').notNull(),
    /** PII per REQ-PRIV-002 — re-fetchable; NOT scrubbed (ADR-0009). */
    givenName: text('given_name').notNull(),
    /** Year only (Eventor returns YYYY-01-01); may be NULL when undisclosed. */
    birthYear: integer('birth_year'),
    /** 'M' / 'F' / NULL — enum enforced at TS layer; SQL stays text. */
    sex: text('sex'),
    /** FK to eventor_clubs.club_id. NULL = orphan (no club affiliation). */
    clubId: integer('club_id').references(() => eventorClubs.clubId),
    /** SportIdent card number. NULL for runners without an SI card. */
    siCard: integer('si_card'),
    /** Emit card number (parallel Norwegian/legacy system). NULL is common. */
    emitCard: integer('emit_card'),
    /** Eventor `modifyTime` parsed to epoch ms. */
    modifyDateMs: integer('modify_date_ms').notNull(),
  },
  (t) => [
    // Partial (non-unique) index on si_card — the walk-up lookup path. Sub-ms
    // by card. NULL si_card is allowed multiply. Card NUMBER duplicates are
    // also tolerated because real Eventor data has them (family-shared
    // cards, replacement cards, rental pool). See plan 02-09.
    index('idx_eventor_si_card_lookup')
      .on(t.siCard)
      .where(sql`${t.siCard} IS NOT NULL`),
    // Plain index for the name-prefix autocomplete path (operator types
    // family name, picker resolves Eventor row → pre-fill).
    index('idx_eventor_name').on(t.familyName, t.givenName),
  ]
);

// ---------------------------------------------------------------------------
// meos_competitors — shadow table mirroring MeOS's <cmp> records (D-MOP-1).
// Populated by the MOP receiver. NO competition_id FK because MeOS state is
// scoped to a single bridge session, not per-competition (MeOS doesn't know
// our UUIDs anyway).
// ---------------------------------------------------------------------------

export const meosCompetitors = sqliteTable('meos_competitors', {
  /** MeOS internal id (32-bit integer). */
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  /** MeOS class id; resolves against meos_classes.id. NULL = unclassed. */
  classId: integer('class_id'),
  /** MeOS organisation id; resolves against meos_clubs.id. NULL = unclubbed. */
  orgId: integer('org_id'),
  /** MeOS status code (0=Unknown, 1=OK, ...). */
  statusCode: integer('status_code').notNull().default(0),
  /** Start time in tenths of a second; NULL if not yet started. */
  startTimeTenths: integer('start_time_tenths'),
  /** Running time in tenths of a second; NULL if not yet finished. */
  runningTimeTenths: integer('running_time_tenths'),
  /** Bib number (text — MeOS allows alphanumeric). */
  bib: text('bib'),
  cardNumber: integer('card_number'),
  /** Epoch ms of the most recent MOP payload that touched this row. */
  lastMopUpdateMs: integer('last_mop_update_ms').notNull(),
});

// ---------------------------------------------------------------------------
// meos_classes — shadow of MeOS class definitions. Name is the JOIN key for
// the D-MOP-3 auto-merge (we match MeOS classes against our `classes.name`).
// ---------------------------------------------------------------------------

export const meosClasses = sqliteTable('meos_classes', {
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  /** Sort-order hint MeOS provides; NULL when unset. */
  ord: integer('ord'),
  lastMopUpdateMs: integer('last_mop_update_ms').notNull(),
});

// ---------------------------------------------------------------------------
// meos_clubs — shadow of MeOS organisation definitions.
// ---------------------------------------------------------------------------

export const meosClubs = sqliteTable('meos_clubs', {
  id: integer('id').primaryKey(),
  name: text('name').notNull(),
  /** ISO 3166-1 alpha-3 country code; NULL = unknown. */
  nat: text('nat'),
  lastMopUpdateMs: integer('last_mop_update_ms').notNull(),
});

// ---------------------------------------------------------------------------
// hired_cards — D-HB-1 junction table for rental SI cards per competition.
// Compound PK on (competition_id, card_number) so the same physical card can
// be loaned at multiple competitions (different events, same hardware) but
// only ONE open rental per competition.
//
// PII per REQ-PRIV-002 — contact_name/phone/email/note are scrubbed by
// privacy/retention.ts (Plan 06 extension). marked_at_ms / returned_at_ms /
// card_number are PRESERVED audit trail (hardware ID + timestamps; not PII).
// ---------------------------------------------------------------------------

export const hiredCards = sqliteTable(
  'hired_cards',
  {
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    cardNumber: integer('card_number').notNull(),
    /** Epoch ms when the operator marked the card as rented. */
    markedAtMs: integer('marked_at_ms').notNull(),
    /** Epoch ms when the operator marked the card as returned. NULL = open. */
    returnedAtMs: integer('returned_at_ms'),
    /** PII (REQ-PRIV-002 scrub list — Plan 06). */
    contactName: text('contact_name'),
    /** PII (REQ-PRIV-002 scrub list — Plan 06). */
    contactPhone: text('contact_phone'),
    /** PII (REQ-PRIV-002 scrub list — Plan 06). */
    contactEmail: text('contact_email'),
    /** Free-form operator note; may contain PII (REQ-PRIV-002 scrub list). */
    note: text('note'),
  },
  (t) => [primaryKey({ columns: [t.competitionId, t.cardNumber] })]
);

// ===========================================================================
// Phase 2.1 — D-15: course_replacements.
//
// Alternative control codes accepted in lieu of the expected control code on
// a given course. The reducer looks up replacement codes before comparing
// expected vs actual punches — if the punched code is in the replacement set
// for the expected code, it counts as a match. One-level lookup only (no
// chaining).
//
// Unique index prevents duplicate mappings for the same (course, expected)
// pair.
// ===========================================================================

export const courseReplacements = sqliteTable(
  'course_replacements',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    courseId: text('course_id')
      .notNull()
      .references(() => courses.id, { onDelete: 'cascade' }),
    /** The expected control code in the course sequence. */
    controlCode: integer('control_code').notNull(),
    /** An alternative punched code that counts as a hit on controlCode. */
    alternativeCode: integer('alternative_code').notNull(),
  },
  (t) => [
    uniqueIndex('course_replacements_unique').on(t.courseId, t.controlCode, t.alternativeCode),
  ]
);
